.TH log_debug 3 "Noviembre 2024" "nanologger 1.0.0" "Manual de funciones de biblioteca"
.SH NOMBRE
log_debug \- Registrar un mensaje de depuración.

.SH SINOPSIS
.B #include <nanologger.h>
.br
.BI "void log_debug(const char *file, int line, const char *func, const char *fmt, ...);"

.SH DESCRIPCIÓN
La función
.B log_debug
registra un mensaje de depuración. Esta función es útil para proporcionar información detallada con fines de depuración.

La función acepta los siguientes parámetros:
.TP
.I file
El nombre del archivo fuente donde se generó el mensaje de depuración.
.TP
.I line
El número de línea en el archivo fuente donde se generó el mensaje de depuración.
.TP
.I func
El nombre de la función donde se generó el mensaje de depuración.
.TP
.I fmt
Una cadena de formato estilo printf, seguida de los argumentos adicionales necesarios.

.SH VALOR DE RETORNO
Esta función no devuelve ningún valor.

.SH NOTAS
Esta función solo está disponible si la macro
.B DEBUG
se establece en 3 o superior.

.SH AUTOR
Escrito por Israel López.

.SH VER TAMBIÉN
.BR log_critical (3),
.BR log_error (3),
.BR log_warn (3)

