.TH log_critical 3 "Noviembre 2024" "nanologger 1.0.0" "Manual de funciones de biblioteca"
.SH NOMBRE
log_critical \- Registrar un mensaje de error crítico.

.SH SINOPSIS
.B #include <nanologger.h>
.br
.BI "void log_critical(const char *file, int line, const char *func, const char *fmt, ...);"

.SH DESCRIPCIÓN
La función
.B log_critical
registra un mensaje de error crítico, normalmente utilizado para errores graves que pueden requerir que el programa se cierre.

La función acepta los siguientes parámetros:
.TP
.I file
El nombre del archivo fuente donde ocurrió el error.
.TP
.I line
El número de línea en el archivo fuente donde ocurrió el error.
.TP
.I func
El nombre de la función donde ocurrió el error.
.TP
.I fmt
Una cadena de formato estilo printf, seguida de los argumentos adicionales necesarios.

.SH VALOR DE RETORNO
Esta función no devuelve ningún valor.

.SH NOTAS
Esta función solo está disponible si la macro
.B DEBUG
se establece en 0 o superior.

.SH AUTOR
Escrito por Israel López.

.SH VER TAMBIÉN
.BR log_error (3),
.BR log_warn (3),
.BR log_debug (3)

