.TH log_init 3 "2024年11月" "nanologger 1.0.0" "库函数手册"
.SH 名称
log_init \- 记录进程或资源的初始化。

.SH 概述
.B #include <nanologger.h>
.br
.BI "void log_init(const char *file, int line, const char *func, const char *fmt, ...);"

.SH 描述
.B log_init
函数记录进程或资源的初始化。

该函数接受以下参数：
.TP
.I file
发生初始化的源文件名称。
.TP
.I line
发生初始化的源文件中的行号。
.TP
.I func
发生初始化的函数名称。
.TP
.I fmt
一个printf风格的格式字符串，后跟所需的其他参数。

.SH 返回值
该函数没有返回值。

.SH 注意
只有在
.B DEBUG
宏设置为3或更高时，此函数才可用。

.SH 作者
由Israel López编写。

.SH 参见
.BR log_end (3),
.BR log_debug (3)

