.TH log_end 3 "November 2024" "nanologger 1.0.0" "Library Functions Manual"
.SH NAME
log_end \- Log the termination of a process or resource.

.SH SYNOPSIS
.B #include <nanologger.h>
.br
.BI "void log_end(const char *file, int line, const char *func, const char *fmt, ...);"

.SH DESCRIPTION
The
.B log_end
function logs the termination of a process or resource.

The function accepts the following parameters:
.TP
.I file
The name of the source file where the termination occurred.
.TP
.I line
The line number in the source file where the termination occurred.
.TP
.I func
The name of the function where the termination occurred.
.TP
.I fmt
A printf-style format string, followed by additional arguments as needed.

.SH RETURN VALUE
This function does not return a value.

.SH NOTES
This function is only available if the
.B DEBUG
macro is set to 3 or higher.

.SH AUTHOR
Written by Israel López.

.SH SEE ALSO
.BR log_init (3),
.BR log_debug (3)

