.TH log_warn 3 "November 2024" "nanologger 1.0.0" "Library Functions Manual"
.SH NAME
log_warn \- Log a warning message.

.SH SYNOPSIS
.B #include <nanologger.h>
.br
.BI "void log_warn(const char *file, int line, const char *func, const char *fmt, ...);"

.SH DESCRIPTION
The
.B log_warn
function logs a warning message. This function is useful for reporting potential issues that do not stop the program.

The function accepts the following parameters:
.TP
.I file
The name of the source file where the warning occurred.
.TP
.I line
The line number in the source file where the warning occurred.
.TP
.I func
The name of the function where the warning occurred.
.TP
.I fmt
A printf-style format string, followed by additional arguments as needed.

.SH RETURN VALUE
This function does not return a value.

.SH NOTES
This function is only available if the
.B DEBUG
macro is set to 2 or higher.

.SH AUTHOR
Written by Israel López.

.SH SEE ALSO
.BR log_critical (3),
.BR log_error (3),
.BR log_debug (3)

